NIP.Adhoc/KendoMVCTemplate/Controllers/XTransactionController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using ZenithBankXpath.Core;
using ZenithBankXpath.Web.Models;

namespace ZenithBankXpath.Web.Controllers
{
    public class XTransactionController : Controller
    {
        // GET: XTransaction
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new TransactionModel());
        }

        [HttpPost]
        public ActionResult Create(TransactionModel model)
        {
            //Session["TransModel"] = model;

            var enmodel = new EncryptModel();
            enmodel.accountNumber = model.AccountNo;
            enmodel.channelId = "10";
            int mid = 0;
            int.TryParse(model.MerchantId, out mid);
            enmodel.merchantId = mid;
            //SecurityHelper sechelper = new SecurityHelper();
            //var param = sechelper.EncryptRendererParam(enmodel);
            var rendurl = "http://172.29.30.43:3000/?param=";// + param;
            return Json(rendurl, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult AccountDetails(string accountno)
        {
            //var A = accountno.Split('|');
            //var account = AccountSingleton.Instance.Accounts.FirstOrDefault(m => m.AccountNo.Trim().Equals(accountno.Trim()));
            //AccountServices asvc = new AccountServices();
            //var acctdetails = asvc.GetAccountDetails(accountno);
            TransactionModel model = new TransactionModel();
            model.AccountNo = accountno;
            //model.AvailableBalance = acctdetails.AvailableBalance;
            //model.Currency = acctdetails.Currency;
            //if(account != null)
            //model.MerchantId = account.MerchantId;
            Session["transmodel"] = model;

            return PartialView("_AccountDetails", model);
        }

        public ActionResult TransactionDetails()
        {
            TransactionModel model = (TransactionModel)Session["transmodel"];

            return PartialView("_TransactionDetails", model);
        }

        public ActionResult AdditionalFields()
        {
            return View(new TransactionModel());
        }

        public ActionResult PostTransaction()
        {
            return View();
        }
        //[HttpPost]
        //public ActionResult PostTransaction()
        //{
        //    return View();
        //}

        public JsonResult GetAccounts(string text)
        {
            //var accounts = ;// = AccountSingleton.Instance.Accounts;

            //if (!string.IsNullOrEmpty(text))
            //{
            //    accounts = accounts.Where(p => p.AccountName.ToLower().Contains(text.ToLower()) 
            //    || p.AccountNo.ToLower().Contains(text.ToLower()) 
            //    || p.MerchantId.ToLower().Contains(text.ToLower())).ToList();
            //}
            return Json(new { }, JsonRequestBehavior.AllowGet);
        }

    }
}

NIP.Adhoc/KendoMVCTemplate/Views/Shared/_AccountDetails.cshtml
@model ZenithBankXpath.Web.Models.TransactionModel

<style>
    .row.display-flex {
        display: flex;
        flex-wrap: wrap;
    }

        .row.display-flex > [class*='col-'] {
            display: flex;
            flex-direction: column;
        }
</style>

<div>
    <div class="form-group">
        @Html.LabelFor(model => model.MerchantId, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.MerchantId, new { @class = "form-control", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.MerchantId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AccountNo, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.AccountNo, new { @class = "form-control", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.AccountNo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Currency, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Currency, new { @class = "form-control", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.Currency, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AvailableBalance, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.AvailableBalance, new { @class = "form-control", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.AvailableBalance, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

        $("#transform").submit(function (e) {
            e.preventDefault();  //prevent normal form submission

            var actionUrl = $(this).attr("action");  // get the form action value

            $.post(actionUrl, $(this).serialize(), function (res) {
                //res is the response coming from our ajax call. Use this to update DOM

                document.getElementById('additionalfields').src = res
                document.getElementById('btnrender').hidden = true

            });
        });

    });

    //function loadiframe() {
    //    $("additionalfields").attr("", "http://172.29.30.43:3000/")
    //}
</script>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
}

NIP.Adhoc/KendoMVCTemplate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Transaction Dash-Board</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    @Styles.Render("~/Content/css")

    <!-- Font Awesome -->
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">*@
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />*@

    <!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
    <link href="~/Content/spinkit.css" rel="stylesheet" />
    <link href="@Url.Content("~/Content/kendo/2017.2.504/kendo.common-bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2017.2.504/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2017.2.504/kendo.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <!-- Bootstrap core CSS -->
    <!-- Material Design Bootstrap -->
    <link href="@Url.Content("~/css/mdb.css")" rel="stylesheet">
    <link href="@Url.Content("~/css/material-bootstrap-wizard.css")" rel="stylesheet" />


    <!-- App favicon -->
    @*<link rel="shortcut icon" href="assets/images/favicon.ico">*@
    <!-- App css -->
    @*<link href="~/Content/kendo/bootstrap.min.css" rel="stylesheet" />*@
    <link href="@Url.Content("~/Content/icons.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/metismenu.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" />
    @*<script src="assets/js/modernizr.min.js"></script>*@
    @*<link href="@Url.Content("~/css/adminlte.css")" rel="stylesheet">*@
    @*<link href="@Url.Content("~/css/bootstrap.css")" rel="stylesheet">*@



    @*@Scripts.Render("~/bundles/modernizr")*@
    @Scripts.Render("~/bundles/jquery")



    <script src="@Url.Content("~/Scripts/kendo/2017.2.504/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2017.2.504/jszip.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2017.2.504/kendo.all.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2017.2.504/kendo.aspnetmvc.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>

    <script type="text/javascript" src="@Url.Content("~/js/popper.min.js")"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="@Url.Content("~/js/bootstrap.min.js")"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="@Url.Content("~/js/mdb.js")"></script>
    <script src="@Url.Content("~/Scripts/waves.js")"></script>
    <script src="@Url.Content("~/js/jquery.bootstrap.js")" type="text/javascript"></script>
</head>


<body>
    <!-- Begin page -->
    <div id="wrapper">
        <!-- Top Bar Start -->
        <div class="topbar">
            <!-- LOGO -->
            <div class="topbar-left">
                <a href="index.html" class="logo">
                    @*<span>
                            <img src="assets/images/logo.png" alt="" height="25">
                        </span>
                        <i>
                            <img src="assets/images/logo_sm.png" alt="" height="28">
                        </i>*@
                </a>
            </div>
            <nav class="navbar-custom">
                <ul class="list-inline float-right mb-0">

                    <li class="list-inline-item dropdown notification-list">
                        <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button"
                           aria-haspopup="false" aria-expanded="false">
                            <img src="~/images/users/img_avatar.png" alt="user" class="rounded-circle">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-dropdown " aria-labelledby="Preview">
                            <!-- item-->
                            <div class="dropdown-item noti-title">
                                <h5 class="text-overflow"><small>Welcome ! John</small> </h5>
                            </div>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="zmdi zmdi-account-circle"></i> <span>Profile</span>
                            </a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="zmdi zmdi-settings"></i> <span>Settings</span>
                            </a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="zmdi zmdi-lock-open"></i> <span>Lock Screen</span>
                            </a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="zmdi zmdi-power"></i> <span>Logout</span>
                            </a>
                        </div>
                    </li>
                </ul>
                <ul class="list-inline menu-left mb-0">
                    <li class="float-left">
                        <button class="button-menu-mobile open-left waves-light waves-effect">
                            <i class="dripicons-menu"></i>
                        </button>
                    </li>
                </ul>
            </nav>
        </div>
        <!-- Top Bar End -->
        <!-- ========== Left Sidebar Start ========== -->
        <div class="left side-menu">
            <div class="slimscroll-menu" id="remove-scroll">
                <!--- Sidemenu -->
                <div id="sidebar-menu">
                    <!-- Left Menu Start -->
                    <ul class="metismenu" id="side-menu">
                        <li class="menu-title">Menu</li>
                        <li>
                            <a href="~/Home/IncomingStatistics" onclick="SetMidBreadCrumb('Incoming')">
                                <i class="fi-arrow-right"></i><span> Incoming </span>
                            </a>
                           
                        </li>
                        <li>
                            <a href="~/Home/OutgoingStatistics" onclick="SetMidBreadCrumb('Outgoing')">
                                <i class="fi-arrow-left"></i><span> Outgoing </span>
                            </a>
                        </li>
                        <li>
                            <a href="~/Home/TransactionSearch" onclick="SetMidBreadCrumb('Transaction Search')">
                                <i class="fi-air-play"></i><span> Transaction Search </span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- Sidebar -->
                <div class="clearfix"></div>
            </div>
            <!-- Sidebar -left -->
        </div>
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box">
                                <h4 class="page-title float-left">Welcome</h4>

                                <ol class="breadcrumb float-right">
                                    <li class="breadcrumb-item"><a href="#">NIP</a></li>
                                    <li class="breadcrumb-item"><a href="#" id="bci-mid">*</a></li>
                                    <li class="breadcrumb-item active" id="bci-last">*</li>
                                </ol>

                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>

                    @RenderBody()
                </div> <!-- container -->
            </div> <!-- content -->
            <footer class="footer text-right">
                2018 © Zenith Bank
            </footer>
        </div>

        <!-- ============================================================== -->
        <!-- End Right content here -->
        <!-- ============================================================== -->

    </div>

    

    <!--  Plugin for the Wizard -->
    <script src="@Url.Content("~/js/material-bootstrap-wizard.js")"></script>

    <!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
    <script src="@Url.Content("~/js/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/js/bootstrap-datagrid.js")"></script>

    <!-- END wrapper -->
    <!-- jQuery  -->
    <script src="@Url.Content("~/Scripts/tether.min.js")"></script>
    @*@Scripts.Render("~/bundles/bootstrap")*@
    <script src="@Url.Content("~/Scripts/metisMenu.min.js")"></script>

    <script src="@Url.Content("~/Scripts/jquery.slimscroll.js")"></script>

    <!--Form Wizard-->
    <script src="@Url.Content("~/Scripts/jquery.stepy.min.js")"></script>
    <!--wizard initialization-->
    <script src="@Url.Content("~/Scripts/jquery.wizard-init.js")"></script>

    <script src="@Url.Content("~/Scripts/jquery.core.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.app.js")"></script>

    @*@Scripts.Render("~/bundles/jqueryval")*@

    @RenderSection("scripts", required: false)
    <script>
        var SetMidBreadCrumb = (d) => {
            $('#bci-mid').text(d)
        }



    </script>
</body>
</html>

NIP.Adhoc/KendoMVCTemplate/Views/Shared/_TransactionDetails.cshtml
@model ZenithBankXpath.Web.Models.TransactionModel

<style>
    .row.display-flex {
        display: flex;
        flex-wrap: wrap;
    }

        .row.display-flex > [class*='col-'] {
            display: flex;
            flex-direction: column;
        }
</style>

@using (Html.BeginForm("Create", "XTransaction", FormMethod.Post, new { id = "transform" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.HiddenFor(model => model.MerchantId)
    @Html.HiddenFor(model => model.AccountNo)
    @Html.HiddenFor(model => model.Currency)
    @Html.HiddenFor(model => model.AvailableBalance)

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.TranCode, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @(Html.Kendo().DropDownList()
                        .Name("TranCode")
                        .DataTextField("Text")
                        .DataValueField("Value")
                        .BindTo(new List<SelectListItem>() {
                        new SelectListItem() {
                            Text = "101 - Deposit",
                            Value = "101"
                        },
                        new SelectListItem() {
                            Text = "102-Transfer Deposit",
                            Value = "102"
                        },
                        new SelectListItem() {
                            Text = "103 - Force Posted Deposit",
                            Value = "103"
                        },
                        new SelectListItem() {
                            Text = "104 - Foreign ATM Deposit",
                            Value = "104"
                        }
                        })
                        .Value("101")
                        .HtmlAttributes(new { style = "width: 100%" })
            )

            @Html.ValidationMessageFor(model => model.TranCode, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TranType, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @(Html.Kendo().DropDownList()
                        .Name("TranType")
                        .DataTextField("Text")
                        .DataValueField("Value")
                        .BindTo(new List<SelectListItem>() {
                        new SelectListItem() {
                            Text = "POS",
                            Value = "POS"
                        },
                        new SelectListItem() {
                            Text = "TRANSFER FORM CHARGE",
                            Value = "TRANSFER FORM CHARGE"
                        },
                        new SelectListItem() {
                            Text = "OTHERS",
                            Value = "OTHERS"
                        },
                        new SelectListItem() {
                            Text = "DUD CHEQUE",
                            Value = "DUD CHEQUE"
                        }
                        })
                        .Value("POS")
                        .HtmlAttributes(new { style = "width: 100%" })
            )
            @Html.ValidationMessageFor(model => model.TranType, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Amount, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group" style="float:right">
            <div class="col-md-offset-2 col-md-10" style="float:right">
                <input id="btnrender" type="submit" value="Next >>" class="btn btn-default" />
            </div>
        </div>*@
</div>
}


@*<script>
    $(document).ready(function () {

        $("#transform").submit(function (e) {
            e.preventDefault();  //prevent normal form submission

            var actionUrl = $(this).attr("action");  // get the form action value

            $.post(actionUrl, $(this).serialize(), function (res) {
                //res is the response coming from our ajax call. Use this to update DOM

                document.getElementById('additionalfields').src = res
                document.getElementById('btnrender').hidden = true

            });
        });

    });

        //function loadiframe() {
        //    $("additionalfields").attr("", "http://172.29.30.43:3000/")
        //}
</script>*@

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
}

NIP.Adhoc/KendoMVCTemplate/Views/Shared/_TransactionDetails_Bk.cshtml
@model ZenithBankXpath.Web.Models.TransactionModel

<style>
    .row.display-flex {
        display: flex;
        flex-wrap: wrap;
    }

        .row.display-flex > [class*='col-'] {
            display: flex;
            flex-direction: column;
        }
</style>

@using (Html.BeginForm("Create", "XTransaction", FormMethod.Post, new { id = "transform" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row display-flex">
            <div class="col-md-4">
                <div class="card-box" style="height: 100% !important">
                    <h5>Account Information</h5>
                    <hr />
                    <div class="form-group">
                        @Html.LabelFor(model => model.MerchantId, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.MerchantId, new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.MerchantId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.AccountNo, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.AccountNo, new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.AccountNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Currency, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Currency, new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.Currency, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.AvailableBalance, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.AvailableBalance, new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.AvailableBalance, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card-box" style="height: 100% !important">
                    <h5>Transaction Information</h5>
                    <hr />
                    <div class="form-group">
                        @Html.LabelFor(model => model.TranCode, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @(Html.Kendo().DropDownList()
                                .Name("TranCode")
                                .DataTextField("Text")
                                .DataValueField("Value")
                                .BindTo(new List<SelectListItem>() {
                                    new SelectListItem() {
                                        Text = "101 - Deposit",
                                        Value = "101"
                                    },
                                    new SelectListItem() {
                                        Text = "102-Transfer Deposit",
                                        Value = "102"
                                    },
                                    new SelectListItem() {
                                        Text = "103 - Force Posted Deposit",
                                        Value = "103"
                                    },
                                    new SelectListItem() {
                                        Text = "104 - Foreign ATM Deposit",
                                        Value = "104"
                                    }
                                })
                                .Value("101")
                                .HtmlAttributes(new { style = "width: 100%" })
                            )

                            @Html.ValidationMessageFor(model => model.TranCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.TranType, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @(Html.Kendo().DropDownList()
                                        .Name("TranType")
                                        .DataTextField("Text")
                                        .DataValueField("Value")
                                        .BindTo(new List<SelectListItem>() {
                                                    new SelectListItem() {
                                                        Text = "POS",
                                                        Value = "POS"
                                                    },
                                                    new SelectListItem() {
                                                        Text = "TRANSFER FORM CHARGE",
                                                        Value = "TRANSFER FORM CHARGE"
                                                    },
                                                    new SelectListItem() {
                                                        Text = "OTHERS",
                                                        Value = "OTHERS"
                                                    },
                                                    new SelectListItem() {
                                                        Text = "DUD CHEQUE",
                                                        Value = "DUD CHEQUE"
                                                    }
                                        })
                                        .Value("POS")
                                        .HtmlAttributes(new { style = "width: 100%" })
                            )
                            @Html.ValidationMessageFor(model => model.TranType, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Amount, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-6" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group" style="float:right">
                        <div class="col-md-offset-2 col-md-10" style="float:right">
                            <input id="btnrender" type="submit" value="Next >>" class="btn btn-default" />
                        </div>
                    </div>
                </div> 
            </div>

            <div class="col-md-4">
                <div class="card-box" style="height: 100% !important; overflow:inherit">
                    <h5>Additional Fields</h5>
                    <hr />
                    <iframe id="additionalfields" src="" style="height:100%; width:100%; border:none"></iframe>
                </div>
            </div>
        </div>

    </div>
}

<script>
    $(document).ready(function () {

        $("#transform").submit(function (e) {
            e.preventDefault();  //prevent normal form submission

            var actionUrl = $(this).attr("action");  // get the form action value

            $.post(actionUrl, $(this).serialize(), function (res) {
                //res is the response coming from our ajax call. Use this to update DOM

                document.getElementById('additionalfields').src = res
                document.getElementById('btnrender').hidden = true

            });
        });

    });

    //function loadiframe() {
    //    $("additionalfields").attr("", "http://172.29.30.43:3000/")
    //}
</script>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
}